spring:
  application:
    name: CUSTOMER-SERVICE
  config:
    import: configserver:http://localhost:8085
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-96813037.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oadast9m8FgXVmRI5d7
            client-secret: T5l-NrJi7fUv4ClDDAwPVgdCWaWVC2Ppjfkc8xRmXJ_dXFvcm5HHuWtRl-PpNOn7
        provider:
          okta:
            issuer-uri: https://dev-96813037.okta.com/oauth2/default

server:
  port: 8081

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingRestaurantBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingRestaurantService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      customerRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-96813037.okta.com/oauth2/default
    audience: api://default